CREATE TABLE "GCG_4687_Production"(
 "ORDER_NO" CHAR(7) NOT NULL ,
 "MECH_SHOP" LONGVARCHAR,
 "MACH_SHOP" LONGVARCHAR,
 "ROTOR_SHOP" LONGVARCHAR,
 "Notes" LONGVARCHAR,
 PRIMARY KEY ("ORDER_NO"));
CREATE UNIQUE INDEX "PK_4687" ON "GCG_4687_Production"("ORDER_NO");